// AUTOGENERATED CONTENT
import { createGlobalStyle } from 'styled-components';

export default createGlobalStyle`
    :root {
        --text-font-family: Hack, monospace;
        --text-font-url: [object Object];
        --text-color-primary: #24292e;
        --text-color-secondary: #586069;
        --text-color-tertiary: #6a737d;
        --text-color-danger: #cb2431;
        --text-color-description: #8b949e;
        --background-color-primary: #fff;
        --background-color-secondary: #0d1117;
        --border-color-primary: #30363d;
        --border-color-secondary: #21262d;
        --link-text-color: #58a6ff;
        --button-text-color: #24292e;
        --button-background-color: #fafbfc;
        --button-background-color-hover: #f3f4f6;
        --button-border-color: rgba(27, 31, 35, 0.15);
        --button-border-color-hover: rgba(27, 31, 35, 0.15);
        --button-box-shadow: 0 1px 0 rgba(27, 31, 35, 0.04), inset 0 1px 0 hsla(0, 0%, 100%, 0.25);
        --button-outline-text-color: #24292e;
        --button-outline-background-color: #fafbfc;
        --button-outline-background-color-hover: #f3f4f6;
        --button-outline-border-color: rgba(27, 31, 35, 0.15);
        --button-outline-border-color-hover: rgba(27, 31, 35, 0.15);
        --button-outline-box-shadow: 0 1px 0 rgba(27, 31, 35, 0.04), inset 0 1px 0 hsla(0, 0%, 100%, 0.25);
        --button-primary-text-color: #fff;
        --button-primary-background-color: #2ea44f;
        --button-primary-background-color-hover: #2ea043;
        --button-primary-border-color: #2ea043;
        --button-primary-border-color-hover: #3fb950;
        --input-text-color: #24292e;
        --input-border-color: #e1e4e8;
        --input-border-color-focus: #17b978;
        --input-background-color: #fafbfc;
        --input-background-color-focus: #fff;
        --input-box-shadow-color: transparent;
        --input-box-shadow-color-focus: rgba(3, 214, 126, 0.3);
        --input-box-shadow-error-color-focus: rgba(214, 3, 13, 0.3);
        --input-placeholder-color: #7c8590;
        --tabs-border-color: #e1e4e8;
        --nav-bar-primary-color: #18e895;
        --nav-bar-border-color-hover: #c8c9ca;
    }
`;
