// AUTOGENERATED CONTENT
import { createGlobalStyle } from 'styled-components';

export default createGlobalStyle`
    :root {
        --text-font-family: Hack, monospace;
        --text-font-url: [object Object];
        --text-color-primary: #fff;
        --text-color-secondary: #c9d1d9;
        --text-color-danger: #ff3d3e;
        --text-color-description: #8b949e;
        --background-color-primary: #161b22;
        --background-color-secondary: #0d1117;
        --border-color-primary: #30363d;
        --border-color-secondary: #21262d;
        --link-text-color: #58a6ff;
        --button-text-color: #c9d1d9;
        --button-background-color: #21262d;
        --button-background-color-hover: #30363d;
        --button-border-color: #30363d;
        --button-border-color-hover: #8b949e;
        --button-primary-text-color: #fff;
        --button-primary-background-color: #238636;
        --button-primary-background-color-hover: #2ea043;
        --button-primary-border-color: #2ea043;
        --button-primary-border-color-hover: #3fb950;
    }
`;
