module.exports = {
    textFontFamily: 'Hack, monospace',
    textFontUrl: { value: '//cdn.jsdelivr.net/npm/hack-font@3/build/web/hack-subset.css' },
    textColorPrimary: '#fff',
    textColorSecondary: '#c9d1d9',
    textColorDanger: '#ff3d3e',
    textColorDescription: '#8b949e',
    backgroundColorPrimary: '#161b22',
    backgroundColorSecondary: '#0d1117',
    borderColorPrimary: '#30363d',
    borderColorSecondary: '#21262d',
    linkTextColor: '#58a6ff',
    buttonTextColor: '#c9d1d9',
    buttonBackgroundColor: '#21262d',
    buttonBackgroundColorHover: '#30363d',
    buttonBorderColor: '#30363d',
    buttonBorderColorHover: '#8b949e',
    buttonPrimaryTextColor: '#fff',
    buttonPrimaryBackgroundColor: '#238636',
    buttonPrimaryBackgroundColorHover: '#2ea043',
    buttonPrimaryBorderColor: '#2ea043',
    buttonPrimaryBorderColorHover: '#3fb950',
};
